### PR TITLE
Bump to 1.0.3

### PR DESCRIPTION
**Pull request by bios21**
Hi there ; 
Since Deno 1.0.3 is out, here a simple PR to bump the version for the layer to be accessible.

It also bump std from 0.52.0 to 0.54.0.

(see https://github.com/hayd/deno-docker/pull/50 for needed docker image)

### CODE REVIEW

**Comment by bios21** [comment]
cc @lucacasonato @hayd

**Comment by bios21** [comment]
Yes, would you allow an empty commit to do that or do you prefer an amend?

**Comment by lucacasonato** [comment]
@bios21 Just reran the tests, but there seem to be some issues. I think you need to update some lock files

**Comment by hayd** [comment]
Thanks @bios21 ! Sorry this seems to be an awkward update (usually it is not).

This is quite tricky to debug. For test_badlock it looks like some error messages were changed slightly in deno itself (maybe?).
```diff
-      "content": "{\"errorMessage\" : \"lock file error: Subresource integrity check failed --lock=badlock.json\nhttps://deno.land/std@v0.38.0/strings/pad.ts\", \"errorType\" : \"InitException\"}"
+      "content": "{\"errorMessage\" : \"lock file error: Compile file:///var/task/pad.ts\nSubresource integrity check failed --lock=badlock.json\nhttps://deno.land/std@v0.38.0/strings/pad.ts\", \"errorType\" : \"InitException\"}"
```


Unfortunately these three: test_config, test_config2, test_importmap failing for me but I am not sure why. All look to be failing to compile... when they should/do compile!

**Comment by lucacasonato** [comment]
1.0.4 was just released and I know Bartek landed some fixes for issues that are related to imports, so I'll create a PR for that and see if that resolves any of the test issues. I'll take a look otherwise.

**Comment by bios21** [comment]
@lucacasonato Should I close this PR then?

**Pull request closed without merging**
