### PR TITLE
Add Terraform Example

### PR DESCRIPTION
**Pull request by Damola12345**
Add terraform example #180 
@hayd kindly review and check it out

### CODE REVIEW

**Comment by hayd** [comment]
Thanks! This is great to have.

Is there a way to test this locally (ideally so we could test it in CI) ?

**Comment by Damola12345** [comment]
is the screenshot enough ? @hayd

**Comment by Damola12345** [comment]
@hayd

**Comment by hayd** [comment]
Apologies for the slow response, this is on my TODO list to review soon.

This is really great thing to have! (Changing the title so at least for the moment people find this PR :) )

**Comment by Damola12345** [comment]
No problem @hayd just take your time.

**Comment by lucacasonato** [comment]
This repo is now archived because we are discontinuing the AWS Lambda layer for Deno. Instead we recommend you use a Docker image on AWS Lambda to run Deno. [You can find a full guide in the docs](https://docs.deno.com/runtime/tutorials/aws_lambda/).

**Pull request closed without merging**
