### PR TITLE
Bump to 1.0.4

### PR DESCRIPTION
**Pull request by lucacasonato**
cc @hayd

### CODE REVIEW

**Comment by hayd** [comment]
Running just test_config (and not piping stderr), I get this:

```
running 1 tests
test test_config ... Compile file:///tmp/runtime.js
error: Uncaught AssertionError: Unexpected skip of the emit.
    at Object.assert ($deno$/util.ts:33:11)
    at compile ($deno$/compiler.ts:1170:7)
    at tsCompilerOnMessage ($deno$/compiler.ts:1338:22)
    at workerMessageRecvCallback ($deno$/runtime_worker.ts:72:33)
    at file:///var/task/__anonymous__:1:1
FAILED (2503ms)

failures:

test_config
AssertionError: Values are not equal:


    [Diff] Actual / Expected


+   [
+     {
+       status: "error",
+       content: "{"errorMessage" : "decorate.ts must export a function named 'handler'", "errorType" : "InitException..."
+     }
+   ]
-   [ { status: "ok", content: "{"statusCode":200,"body":"decorated 🦕"}" } ]
```

"Unexpected skip of the emit." is concerning.

**Comment by lucacasonato** [comment]
Yeah that looks like a Deno bug.

**Comment by hayd** [comment]
I am thinking I should disable these tests and manually test the bundle on lambda (with these flags specifically). I have been unable to replicate the issue to a smaller test case. It is very strange.

**Comment by bios21** [comment]
Is there any improvement since the 1.0.5 is out?

**Comment by hayd** [comment]
we're waiting for 1.1 when the above fix landed, should be released in a couple of days.

**Pull request closed without merging**
