### PR TITLE
Added a space on line 17

### PR DESCRIPTION
**Pull request by Alon2303**

### CODE REVIEW

**Comment by hayd** [comment]
This is confusing, I have `deno fmt` in the CI - why would this not be caught here? Any ideas?

https://github.com/hayd/deno-lambda/blob/c0d4b48b4e464eafe2e127774d66d59fe5fbda3e/.github/workflows/fmt_lint.yml#L8-L11

**Comment by Alon2303** [comment]
not sure..

**Comment by hayd** [comment]
It's strange fmt is fine with either... I wonder if this a bug in `deno fmt` (or does prettier also do this) ?

Example (fmt check is okay):
```ts
function foo() {}

function bar() {}
function baz() {}
```

**Comment by hayd** [comment]
Also: thank you for this, it seems like a good/reasonable change 👍

**Comment by hayd** [comment]
🤷 : https://github.com/prettier/prettier/issues/879#issuecomment-284309238

thanks!

**Pull request merged**
