### PR TITLE
chore: bump to Deno 1.5.0

### PR DESCRIPTION
**Pull request by lucacasonato**
cc @hayd

### CODE REVIEW

**Comment by hayd** [comment]
Looks like [dynamodb](https://github.com/chiefbiiko/dynamodb/) needs an update upstream. (and small update in lockfile error string).

I'm not sure if we even can deploy with failing tests, but we could comment the serverless example out for now.

**Comment by kyeotic** [comment]
@hayd That seems like a strange dependency for a runtime layer to have. How is that dynamodb client being used?

**Comment by hayd** [comment]
@kyeotic it's an example only.

**Comment by lucacasonato** [comment]
Totally forgot about this. I will deal with it today or tomorrow.

**Pull request closed without merging**
