### PR TITLE
Bump to 1.0.1

### PR DESCRIPTION
**Pull request by lucacasonato**
cc @hayd

### CODE REVIEW

**Comment by lucacasonato** [comment]
Blocked upstream by https://github.com/denoland/deno/issues/5715. Should I just disable the decorator test for now?

**Comment by hayd** [comment]
Confusing this changed from 1.0.0. is it all config or just decorators? (It's surprising error.)

Thanks for doing these update PRs!

**Comment by lucacasonato** [comment]
Just decorators. Anything else in the config we can test instead? Can't think of any other TypeScript compiler options that would work.

**Comment by hayd** [comment]
> Should I just disable the decorator test for now?

Yes please!

**Pull request merged**
