### PR TITLE
Bump deno version to 1.0.0

### PR DESCRIPTION
**Pull request by hayd**

### CODE REVIEW

**Comment by hayd** [comment]
cc @lucacasonato 

interesting error:
```
thread 'main' panicked at 'Bad file URL for source map: ()', cli/tsc.rs:633:35
```

**Comment by lucacasonato** [comment]
> cc @lucacasonato
> 
> interesting error:
> 
> ```
> thread 'main' panicked at 'Bad file URL for source map: ()', cli/tsc.rs:633:35
> ```

Interesting indeed. This is what I got so far: https://github.com/denoland/deno/issues/5293

**Comment by hayd** [comment]
I wonder why it used the relative form rather than the full (or why I wouldn't use /tmp/deno_dir as in the bootstrap )... perhaps no reason!
🤷 

Thanks for pushing the fix, lgtm, I will tag it!

**Comment by hayd** [comment]
Oh right, it _needs_ to have the deno_dir inside that directory for zipping :)

**Pull request merged**
